services:
  - name: Meals_Budgeting_App
    type: web
    buildCommand: ./build.sh
    startCommand: ./start.sh
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my-database
          property: connectionString
    healthCheckPath: /healthcheck
